import { Octokit } from "@octokit/rest";

export interface PushResult {
  success: boolean;
  repoUrl?: string;
  error?: string;
}

export async function getGithubUser(pat: string): Promise<string | null> {
  try {
    const octokit = new Octokit({ auth: pat });
    const { data } = await octokit.rest.users.getAuthenticated();
    return data.login;
  } catch {
    return null;
  }
}

export async function pushToGitHub(
  pat: string,
  repoName: string,
  artifacts: Record<string, string>,
  description: string
): Promise<PushResult> {
  const octokit = new Octokit({ auth: pat });

  let owner: string;
  try {
    const { data } = await octokit.rest.users.getAuthenticated();
    owner = data.login;
  } catch {
    return { success: false, error: "PAT authentication failed" };
  }

  // Create repo
  try {
    await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName, description, auto_init: false, private: false,
    });
  } catch (e: unknown) {
    if (!String(e).includes("name already exists"))
      return { success: false, error: `Create repo failed: ${String(e)}` };
  }

  // Seed with initial commit via Contents API (works on empty repos)
  try {
    await octokit.rest.repos.createOrUpdateFileContents({
      owner, repo: repoName, path: "README.md",
      message: "chore: init",
      content: Buffer.from(`# ${repoName}\n\nGenerated by MADC-SYS\n`).toString("base64"),
    });
  } catch { /* already has content */ }

  // Get HEAD
  const { data: ref } = await octokit.rest.git.getRef({ owner, repo: repoName, ref: "heads/main" });
  const headSha = ref.object.sha;
  const { data: headCommit } = await octokit.rest.git.getCommit({ owner, repo: repoName, commit_sha: headSha });

  // Build tree
  const treeItems: { path: string; mode: "100644"; type: "blob"; sha: string }[] = [];
  for (const [filePath, content] of Object.entries(artifacts)) {
    const { data: blob } = await octokit.rest.git.createBlob({
      owner, repo: repoName,
      content: Buffer.from(content).toString("base64"),
      encoding: "base64",
    });
    treeItems.push({ path: filePath, mode: "100644", type: "blob", sha: blob.sha });
  }

  const { data: tree } = await octokit.rest.git.createTree({
    owner, repo: repoName, tree: treeItems, base_tree: headCommit.tree.sha,
  });

  const { data: commit } = await octokit.rest.git.createCommit({
    owner, repo: repoName,
    message: `feat: MADC-SYS generated — ${new Date().toISOString()}`,
    tree: tree.sha, parents: [headSha],
  });

  await octokit.rest.git.updateRef({
    owner, repo: repoName, ref: "heads/main", sha: commit.sha,
  });

  return { success: true, repoUrl: `https://github.com/${owner}/${repoName}` };
}
