import { BaseAgent, AgentContext, AgentResult } from "./base-agent.js";

export class CodeGenerationAgent extends BaseAgent {
  readonly name = "CodeGenerationAgent";
  readonly stage = "IMPLEMENTATION";
  readonly icon = "4.";

  async execute(ctx: AgentContext): Promise<AgentResult> {
    await this.sleep(this.rand(800, 1300));

    const files = this.generateFiles(ctx);
    const keys = Object.keys(files);

    const summary = [
      "CODE GENERATION COMPLETE",
      `Language : ${ctx.language}`,
      `Files    : ${keys.length}`,
      "",
      ...keys.map((f) => "  + " + f),
    ].join("\n");

    ctx.bus.publish(this.name, "ReviewAgent", "IMPLEMENTATION", { files: keys }, "COMPLETE");
    return { success: true, output: summary, artifacts: files };
  }

  private generateFiles(ctx: AgentContext): Record<string, string> {
    const { projectName: name, language: lang, request } = ctx;
    const e = this.ext(lang);
    const slug = name.toLowerCase().replace(/\s+/g, "-");
    const files: Record<string, string> = {};

    files[`src/index.${e}`] = this.entry(lang, name);
    files[`src/app.${e}`] = this.app(lang, name);
    files[`src/config.${e}`] = this.config(lang, slug);
    files[`src/logger.${e}`] = this.logger(lang);

    if (/api|rest|http|server/i.test(request)) {
      files[`src/routes/${slug}.${e}`] = this.route(lang, slug);
    }
    if (/db|database|sql|store/i.test(request)) {
      files[`src/db/schema.sql`] = this.schema(slug);
      files[`src/db/repository.${e}`] = this.repo(lang, slug);
    }
    if (/cli|terminal|command/i.test(request)) {
      files[`src/cli.${e}`] = this.cli(lang, name);
    }

    const fileList = Object.keys(files).map((f) => "- " + f).join("\n");
    files["README.md"] = ["# " + name, "", "Generated by MADC-SYS (Termux edition)", "", "## Files", fileList, ""].join("\n");
    return files;
  }

  private entry(lang: string, name: string): string {
    if (lang === "Python") return `# ${name}\nfrom app import App\nif __name__ == "__main__":\n    App().run()\n`;
    if (lang === "Go") return `package main\nfunc main() { Run() }\n`;
    return `import { App } from "./app";\nconst app = new App();\napp.start();\n`;
  }

  private app(lang: string, name: string): string {
    if (lang === "Python") return `class App:\n    def __init__(self):\n        self.name = "${name}"\n    def run(self):\n        print(f"[{self.name}] running")\n`;
    if (lang === "Go") return `package main\ntype App struct{ Name string }\nfunc Run() { a := App{Name: "${name}"}; _ = a }\n`;
    return `export class App {\n  constructor(private name = "${name}") {}\n  start() { console.log(\`[\${this.name}] starting\`); }\n}\n`;
  }

  private config(lang: string, slug: string): string {
    if (lang === "Python") return `import os\nCONFIG = {"app_name": "${slug}", "port": int(os.getenv("PORT", "3000"))}\n`;
    if (lang === "Go") return `package config\nimport "os"\nvar AppName = "${slug}"\nvar Port = os.Getenv("PORT")\n`;
    return `export const config = { appName: "${slug}", port: parseInt(process.env.PORT ?? "3000") };\n`;
  }

  private logger(lang: string): string {
    if (lang === "Python") return `import logging\nlogging.basicConfig(level=logging.INFO)\nlogger = logging.getLogger(__name__)\n`;
    if (lang === "Go") return `package logger\nimport "log"\nfunc Info(msg string) { log.Println("[INFO]", msg) }\n`;
    return `export const logger = {\n  info: (m: string) => console.log(\`[INFO] \${m}\`),\n  warn: (m: string) => console.warn(\`[WARN] \${m}\`),\n  error: (m: string) => console.error(\`[ERR ] \${m}\`),\n};\n`;
  }

  private route(lang: string, slug: string): string {
    if (lang === "Python") return `from flask import Blueprint, jsonify\nbp = Blueprint("${slug}", __name__)\n@bp.get("/${slug}")\ndef list_items(): return jsonify([])\n`;
    return `import { Router } from "express";\nexport const router = Router();\nrouter.get("/${slug}", (_req, res) => res.json({ items: [] }));\nrouter.post("/${slug}", (req, res) => res.json({ created: req.body }));\n`;
  }

  private schema(slug: string): string {
    const t = slug.replace(/-/g, "_");
    return `CREATE TABLE IF NOT EXISTS ${t} (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  created_at TIMESTAMPTZ DEFAULT NOW(),\n  updated_at TIMESTAMPTZ\n);\n`;
  }

  private repo(lang: string, slug: string): string {
    const cls = slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()).replace(/\s/g, "");
    if (lang === "Python") return `class ${cls}Repo:\n    def find_all(self): return []\n    def find_by_id(self, id): return None\n    def save(self, item): return item\n`;
    return `export class ${cls}Repository {\n  async findAll() { return []; }\n  async findById(id: string) { return null; }\n  async save(item: unknown) { return item; }\n}\n`;
  }

  private cli(lang: string, name: string): string {
    if (lang === "Python") return `import argparse\ndef main():\n    p = argparse.ArgumentParser(description="${name}")\n    p.add_argument("cmd")\n    args = p.parse_args()\n    print(f"cmd: {args.cmd}")\n`;
    return `import { parseArgs } from "node:util";\nconst { values } = parseArgs({ options: { cmd: { type: "string" } } });\nconsole.log("[${name}]", values.cmd);\n`;
  }
}
